title: Moonscraper Chart Editor
description: Moonscraper Chart Editor is a song editor for Guitar Hero style rhythm games, primarily intended to support the custom song creation community for games such as Guitar Hero 3, Clone Hero and Rock Band and more.
remote_theme: "jekyll/minima@c6e74bb"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
minima:
  skin: dark